#Use Alpine Linux as the docker base. 
FROM alpine:3.7

#update Alpine image
RUN apk update

#Install nmap
RUN apk add nmap

RUN apk add nmap-scripts

#Install Python
RUN apk add python

#Install Pip
RUN apk add py-pip

#Upgrade Pip to the latest
RUN pip install --upgrade pip

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

#RUN nmap -v scanme.nmap.org

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Run app.py when the container launches
CMD ["python", "app.py"]