#Use Alpine Linux as the docker base. 
FROM amd64/ubuntu

#update 
RUN apt-get update

#Install nmap
RUN apt-get -y install nmap

#Install Python
RUN apt-get -y install python

#Install Pip
RUN apt-get -y install python3-pip

#Install nikto
RUN apt-get -y install nikto

#Upgrade Pip to the latest
RUN pip3 install --upgrade pip

RUN apt-get install -y python3-venv
# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

#Useful to prove that nmap works
#RUN nmap -v scanme.nmap.org

RUN python3 -m venv venv
# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Run app.py when the container launches
CMD ["python", "app.py"]
